# Site settings
title: Adrian Grozavu - SW Engineer, space enthusiast, Linux and open-source software advocate
email: adrianb.grozavu@gmail.com
url: https://s-brody.github.io
description: "Adrian Grozavu - SW Engineer, space enthusiast, Linux and open-source. You have reached my personal webpage"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Adrian Grozavu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/adrian_grozavu
  - title: facebook
    url: https://facebook.com/callsign_brody
  - title: stack-overflow
    url: http://stackoverflow.com/users/2128802/s-brody
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/s-brody

# Build settings
markdown: kramdown
permalink: pretty
